default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

development:
  <<: *default
  database: appointment_scheduler_development

test:
  <<: *default
  database: appointment_scheduler_test

production:
  <<: *default
  database: appointment_scheduler_production
  username: sharvy
  password: <%= ENV['YOUR_APP_NAME_DATABASE_PASSWORD'] %>