# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d72efa280e4e2301638ae1ba426870a358dc5791c7f836de41f9fbcced3ed52c0cb7b467a0ed9387a128228d72615a1d7dc5e08db1341aa2c6c48ff37a947519

test:
  secret_key_base: 74642ce29c36c6642dd54e00a83bc4e83b3d79eb563a092a81a730d25a7a67bdbb8b3cea94aeb32f2cae980a855e1a22c69189819fdc234b386511164b087974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d72efa280e4e2301638ae1ba426870a358dc5791c7f836de41f9fbcced3ed52c0cb7b467a0ed9387a128228d72615a1d7dc5e08db1341aa2c6c48ff37a947519
